---
- name: Install NUT packages
  apt:
    name: ["nut", "nut-client", "nut-server"]
    state: present
    update_cache: true
    autoremove: true
    autoclean: true
  register: apt_result

- name: Reboot server
  reboot:
  when: apt_result.changed

- name: Create NUT configuration directory
  file:
    path: /var/run/nut/
    state: directory
    owner: "{{ nut_user }}"
    group: "{{ nut_group }}"
    mode: 0660

- name: Find configuration files
  find:
    path: /etc/nut
    file_type: file
  register: find_result

- name: Fix configuration file permissions
  file:
    path: "{{ item.path }}"
    owner: root
    group: "{{ nut_group }}"
    mode: 0640
  with_items: "{{ find_result.files }}"

- name: Fix configuration directory permissions
  file:
    path: /etc/nut
    state: directory
    owner: root
    group: "{{ nut_group }}"
    mode: 0755
# - name: Create certificate
#   block:
#     - name: Generate a self signed OpenSSL certificate
#       command: openssl req -new -x509 -nodes -days 3650 -out /tmp/upsd.crt -keyout /tmp/upsd.key -subj "/C=US"
#       args:
#         creates: /tmp/upsd.crt

#     - name: Generate a self signed OpenSSL certificate
#       command: openssl x509 -hash -noout -in /tmp/upsd.crt
#       register: cert_hash

#     # cat upsd.crt upsd.key > upsd.pem
#     # chown root:nut upsd.pem
#     # chmod 0640 upsd.pem

#     - name: Create PEM certificate
#       shell: cat /tmp/upsd.crt /tmp/upsd.key > /tmp/upsd.pem
#       args:
#         creates: /tmp/upsd.pem

#     - name: Set permissions
#       file:
#         src: "{{ item }}"
#         user: "{{ nut_user }}"
#         group: "{{ nut_group }}"
#       with_items:
#         - /tmp/

#   tags: wip
#   run_once: true
